version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

    networks:
      - freelancer

volumes:
  mongo_data:
networks:
  freelancer:
    driver: bridge
