version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
        max-file: '3'
        labels: 'dev_status'
        env: 'os'
    volumes:
      - ./mongo/config/mongod.conf:/etc/mongod.conf
      - ./mongo/config:/data/configdb
      - ./mongo/data:/data/db
      - ./mongo/logs:/var/log/mongodb
    command:
      - '-f'
      - '/etc/mongod.conf'
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    networks:
      - freelancer

volumes:
  mongo_data:
networks:
  freelancer:
    driver: bridge
